name: karmaos-pc
base: core24
version: "26.01"
summary: KarmaOS PC gadget
description: |
  KarmaOS 26.01 - A beautiful Ubuntu Core based desktop OS
  Custom PC gadget with KarmaOS branding
grade: devel
confinement: strict
type: gadget
platforms:
  amd64:

parts:
  gadget:
    plugin: nil
    source: .
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL
      # Copie les configs
      cp -r ${CRAFT_PART_SRC}/*.yaml ${CRAFT_PART_SRC}/*.conf $CRAFT_PART_INSTALL/ 2>/dev/null || true
      # Cloud-init config
      mkdir -p $CRAFT_PART_INSTALL/cloud-init
      cp ${CRAFT_PART_SRC}/cloud.conf $CRAFT_PART_INSTALL/cloud-init/ 2>/dev/null || true
      
  pc-boot:
    plugin: nil
    source: .
    stage-packages:
      - grub-efi-amd64-bin
      - grub-pc-bin
      - shim-signed
    override-build: |
      craftctl default
      # Les binaires GRUB seront copiés automatiquement
