name: karmaos-welcome
base: core24
version: '26.01'
summary: KarmaOS graphical welcome and setup wizard
description: |
  KarmaOS Welcome is a beautiful graphical setup wizard that runs on first boot.
  It guides users through:
  - Network configuration
  - User account creation
  - Application selection and installation
  - System configuration
  
  After setup completes, it automatically removes itself to save space.

grade: devel
confinement: strict

apps:
  karmaos-welcome:
    command: bin/karmaos-welcome-gui.py
    plugs:
      - network
      - network-bind
      - network-control
      - snapd-control
      - wayland
      - x11
      - desktop
      - desktop-legacy
      - home

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: org.karmaos.Welcome

plugs:
  snapd-control:
    interface: snapd-control

parts:
  karmaos-welcome:
    plugin: dump
    source: src/
    stage-packages:
      - python3
      - python3-gi
      - python3-dbus
      - gir1.2-gtk-3.0
      - gir1.2-vte-2.91
    organize:
      '*.py': bin/
      '*.sh': bin/
    override-stage: |
      craftctl default
      chmod +x $CRAFT_STAGE/bin/*.sh
      chmod +x $CRAFT_STAGE/bin/*.py
      
  assets:
    plugin: dump
    source: assets/
    organize:
      '*': share/karmaos/
